excel_path: data.xlsx  # Путь по умолчанию (можно изменить через GUI)
google_sheet_id: your-google-sheet-id-here  # ID из URL Google Таблицы
credentials_path: credentials.json  # Путь к файлу авторизации
sheet_mapping:  # Маппинг листов Excel → Google
  Sheet1: Лист1
  Sheet2: Лист2
column_mapping:  # Маппинг колонок
  source: ['A', 'C', 'E']  # Колонки из Excel
  target: ['B', 'D', 'F']  # Куда копировать в Google
start_row: 2  # С какой строки начинать (1 = первая строка)